# packages in environment at /home/lmwhitmore/miniconda3/envs/tf:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   2.1.0                    pypi_0    pypi
anaconda-anon-usage       0.4.4           py312hfc0e8ea_100  
archspec                  0.2.3              pyhd3eb1b0_0  
astunparse                1.6.3                    pypi_0    pypi
boltons                   23.0.0          py312h06a4308_0  
brotli-python             1.0.9           py312h6a678d5_7  
bzip2                     1.0.8                h5eee18b_5  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2024.2.2        py312h06a4308_0  
cffi                      1.16.0          py312h5eee18b_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     24.3.0          py312h06a4308_0  
conda-content-trust       0.2.0           py312h06a4308_0  
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0  
conda-package-handling    2.2.0           py312h06a4308_0  
conda-package-streaming   0.9.0           py312h06a4308_0  
contourpy                 1.2.1                    pypi_0    pypi
cryptography              42.0.5          py312hdda0065_0  
cuda-nvcc                 12.2.91                       0    nvidia/label/cuda-12.2.0
cycler                    0.12.1                   pypi_0    pypi
distro                    1.8.0           py312h06a4308_0  
expat                     2.5.0                h6a678d5_0  
flatbuffers               24.3.25                  pypi_0    pypi
fmt                       9.1.0                hdb19cb5_0  
fonttools                 4.51.0                   pypi_0    pypi
gast                      0.5.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.62.2                   pypi_0    pypi
h5py                      3.11.0                   pypi_0    pypi
icu                       73.1                 h6a678d5_0  
idna                      3.4             py312h06a4308_0  
jsonpatch                 1.33            py312h06a4308_0  
jsonpointer               2.1                pyhd3eb1b0_0  
keras                     3.3.3                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
krb5                      1.20.1               h143b758_1  
ld_impl_linux-64          2.38                 h1181459_1  
libarchive                3.6.2                h6ac8c49_2  
libclang                  18.1.1                   pypi_0    pypi
libcurl                   8.5.0                h251f7ec_0  
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libffi                    3.4.4                h6a678d5_0  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libmamba                  1.5.8                hfe524e5_1  
libmambapy                1.5.8           py312h2dafd23_1  
libnghttp2                1.57.0               h2d74bed_0  
libsolv                   0.7.24               he621ea3_0  
libssh2                   1.10.0               hdbd6064_2  
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
libxml2                   2.10.4               hf1b16e4_1  
lz4-c                     1.9.4                h6a678d5_0  
markdown                  3.6                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
matplotlib                3.8.4                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
menuinst                  2.0.2           py312h06a4308_0  
ml-dtypes                 0.3.2                    pypi_0    pypi
namex                     0.0.8                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu12        12.3.4.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.3.101                 pypi_0    pypi
nvidia-cuda-nvcc-cu12     12.3.107                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.3.107                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.3.101                 pypi_0    pypi
nvidia-cudnn-cu12         8.9.7.29                 pypi_0    pypi
nvidia-cufft-cu12         11.0.12.1                pypi_0    pypi
nvidia-curand-cu12        10.3.4.107               pypi_0    pypi
nvidia-cusolver-cu12      11.5.4.101               pypi_0    pypi
nvidia-cusparse-cu12      12.2.0.103               pypi_0    pypi
nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.3.101                 pypi_0    pypi
opencv-python             4.9.0.80                 pypi_0    pypi
openssl                   3.0.13               h7f8727e_0  
opt-einsum                3.3.0                    pypi_0    pypi
optree                    0.11.0                   pypi_0    pypi
packaging                 23.2            py312h06a4308_0  
pandas                    2.2.2                    pypi_0    pypi
pcre2                     10.42                hebb0a14_0  
pillow                    10.3.0                   pypi_0    pypi
pip                       23.3.1          py312h06a4308_0  
platformdirs              3.10.0          py312h06a4308_0  
pluggy                    1.0.0           py312h06a4308_1  
protobuf                  4.25.3                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pybind11-abi              4                    hd3eb1b0_1  
pycosat                   0.6.6           py312h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.17.2                   pypi_0    pypi
pyparsing                 3.1.2                    pypi_0    pypi
pysocks                   1.7.1           py312h06a4308_0  
python                    3.12.2               h996f2a0_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
pytz                      2024.1                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
reproc                    14.2.4               h295c915_1  
reproc-cpp                14.2.4               h295c915_1  
requests                  2.31.0          py312h06a4308_1  
rich                      13.7.1                   pypi_0    pypi
ruamel.yaml               0.17.21         py312h5eee18b_0  
seaborn                   0.13.2                   pypi_0    pypi
setuptools                68.2.2          py312h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tensorboard               2.16.2                   pypi_0    pypi
tensorboard-data-server   0.7.2                    pypi_0    pypi
tensorflow                2.16.1                   pypi_0    pypi
termcolor                 2.4.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
tqdm                      4.65.0          py312he106c6f_0  
truststore                0.8.0           py312h06a4308_0  
typing-extensions         4.11.0                   pypi_0    pypi
tzdata                    2024.1                   pypi_0    pypi
urllib3                   2.1.0           py312h06a4308_1  
werkzeug                  3.0.2                    pypi_0    pypi
wheel                     0.41.2          py312h06a4308_0  
wrapt                     1.16.0                   pypi_0    pypi
xz                        5.4.6                h5eee18b_0  
yaml-cpp                  0.8.0                h6a678d5_0  
zlib                      1.2.13               h5eee18b_0  
zstandard                 0.19.0          py312h5eee18b_0  
zstd                      1.5.5                hc292b87_0  
